version: 2

models:
  - name: monthly_exchange_rates
    description: "Last available exchange rate for each currency pair per month"
    columns:
      - name: base_currency_id
        description: "Base currency ID"
        data_tests:
          - not_null
      - name: quote_currency_id
        description: "Quote currency ID"
        data_tests:
          - not_null
      - name: month
        description: "Month start date"
        data_tests:
          - not_null
      - name: last_rate
        description: "Last available exchange rate for the month"
        data_tests:
          - not_null

  - name: monthly_asset_values
    description: "Last available value for each asset per month in original currency"
    columns:
      - name: asset_id
        description: "Asset unique identifier"
        data_tests:
          - not_null
      - name: month
        description: "Month start date"
        data_tests:
          - not_null
      - name: last_date
        description: "Last date with available data in the month"
        data_tests:
          - not_null
      - name: currency_name
        description: "Asset's original currency"
        data_tests:
          - not_null
      - name: last_value
        description: "Asset value on last available date"
        data_tests:
          - not_null

  - name: monthly_asset_totals
    description: "Aggregated asset counts and total values per currency per month"
    columns:
      - name: month
        description: "Month start date"
        data_tests:
          - not_null
      - name: currency_name
        description: "Currency name"
        data_tests:
          - not_null
      - name: num_assets
        description: "Number of distinct assets in this currency"
        data_tests:
          - not_null
      - name: total_value
        description: "Sum of all asset values in this currency"
        data_tests:
          - not_null

  - name: monthly_asset_values_all_currencies
    description: "Asset values converted to all available reporting currencies"
    columns:
      - name: month
        description: "Month start date"
        data_tests:
          - not_null
      - name: asset_name
        description: "Asset name"
        data_tests:
          - not_null
      - name: original_currency
        description: "Asset's original currency"
        data_tests:
          - not_null
      - name: reporting_currency
        description: "Target reporting currency"
        data_tests:
          - not_null
      - name: value
        description: "Asset value converted to reporting currency"

  - name: monthly_asset_totals_all_currencies
    description: "Asset totals per original currency converted to all reporting currencies"
    columns:
      - name: month
        description: "Month start date"
        data_tests:
          - not_null
      - name: original_currency
        description: "Original currency of assets"
        data_tests:
          - not_null
      - name: reporting_currency
        description: "Target reporting currency"
        data_tests:
          - not_null
      - name: num_assets
        description: "Number of assets in original currency"
        data_tests:
          - not_null
      - name: total_value
        description: "Total value converted to reporting currency"

  - name: portfolio_total_all_currencies
    description: "Total portfolio value across all assets in each reporting currency"
    columns:
      - name: month
        description: "Month start date"
        data_tests:
          - not_null
      - name: reporting_currency
        description: "Target reporting currency"
        data_tests:
          - not_null
      - name: porfolio_total
        description: "Total portfolio value in reporting currency"
        data_tests:
          - not_null
