version: 2

models:
  - name: stg_currencies
    description: "Staging - currencies from source"
    columns:
      - name: currency_id
        data_tests:
          - unique
          - not_null
      - name: currency_name
        data_tests:
          - not_null

  - name: stg_assets
    description: "Staging - assets from source"
    columns:
      - name: asset_id
        data_tests:
          - unique
          - not_null
      - name: currency_id
        data_tests:
          - not_null
      - name: asset_name
        data_tests:
          - not_null

  - name: stg_asset_values
    description: "Staging - asset values from source"
    columns:
      - name: value_id
        data_tests:
          - unique
          - not_null
      - name: asset_id
        data_tests:
          - not_null
      - name: value
        data_tests:
          - not_null
      - name: date
        data_tests:
          - not_null

  - name: stg_currency_pairs
    description: "Staging - currency pairs from source"
    columns:
      - name: currency_pair_id
        data_tests:
          - unique
          - not_null
      - name: base_currency_id
        data_tests:
          - not_null
      - name: quote_currency_id
        data_tests:
          - not_null

  - name: stg_exchange_rates
    description: "Staging - exchange rates from source"
    columns:
      - name: currency_pair_id
        data_tests:
          - not_null
      - name: rate
        data_tests:
          - not_null
      - name: date
        data_tests:
          - not_null

  - name: all_currencies
    description: "All distinct currencies"
    columns:
      - name: currency_id
        data_tests:
          - unique
          - not_null
      - name: currency_name
        data_tests:
          - not_null

  - name: stg_available_pairs
    description: "Available currency pairs with names"
    columns:
      - name: currency_pair_name
        data_tests:
          - not_null

  - name: stg_all_currencies
    description: "All distinct currencies"
    columns:
      - name: currency_id
        data_tests:
          - unique
          - not_null
      - name: currency_name
        data_tests:
          - not_null
